apiVersion: apps/v1
kind: Deployment
metadata:
  name: knote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knote
  template:
    metadata:
      labels:
        app: knote
    spec:
      containers:
        - name: app
          image: rostirosti/knote-js:1.0.0
          ports:
            - containerPort: 3000
          env:
            - name: NEW_RELIC_LICENSE_KEY
              value: yourkeyhere
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always